### ISSUE TITLE
Support for CANOpen?

### ISSUE THREAD

**Issue by ufechner7** [tsabelmann/CANalyze.jl#12]
Is there any support for CANOpen planned, e.g. sending and receiving SDO and PDO objects?

**Comment by tsabelmann** [comment]
Hello @ufechner7, I have to admit that this package is currently in some kind of hiatus. This package is intended to be used to analyze CAN bus data. Is there a repository package targeting Julia that can send CAN bus data and supports CANOpen?

**Comment by ufechner7** [comment]
Well, I wrote some code for analyzing CAN bus log files (did not know about your package) and will work on CANopen later this year. The question for me is if I shall contribute to this repository or rather create a separate package?

**Comment by tsabelmann** [comment]
I think you should start a new package for your use case because I currently do not have time to work on this Julia package.
